name: 'build and push registry'
inputs:
  key:
    required: true
  image:
    required: true
  target:
    description: 'docker-cli --target option'
    default: ''
  workload_identity_provider:
    required: true
  service_account:
    required: true
  dockerfile:
    default: ''
  build-args:
    default: ''
  context:
    default: ''
runs:
  using: "composite"
  steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.key }}

    - name: OICD Setup
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure docker for artifact registry
      shell: bash
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        target: ${{ inputs.target }}
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        build-args: ${{ inputs.build-args }}
        push: true
        tags: ${{ inputs.image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=maxg

    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

